name: read_novel
description: Read Novel

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  adaptive_theme: ^3.1.1
  velocity_x: ^3.5.1
  rx_shared_preferences: ^3.0.0
  singleton: ^0.0.3-nullsafety
  stacked: ^2.3.15
  double_back_to_close_app: ^2.1.0
  flutter_svg: ^1.1.2
  dio: ^4.0.6
  intl: ^0.17.0
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.1.0
  skeletons: ^0.0.3
  carousel_slider: ^4.1.1
  expandable: ^5.0.1
  webview_flutter: ^3.0.4
  dynamic_height_grid_view: ^0.0.3
  nb_utils: ^4.6.19
  pull_to_refresh_flutter3: ^2.0.1
  flutter_native_splash: ^2.2.7
  easy_rich_text: '^1.1.0'
  path: ^1.8.1
  google_sign_in: ^5.4.1
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  flutter_facebook_auth: ^4.4.1
  modal_bottom_sheet: ^2.1.0
  firebase_crashlytics: ^2.8.8
  flutter_widget_from_html: ^0.8.5
  hidable: ^1.0.2
  flutter_windowmanager: ^0.2.0
  basic_utils: ^5.1.1
  html_editor_enhanced: ^2.5.0
  side_navigation: ^1.0.2
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  fluttertoast: ^8.0.9
  flutter_datetime_picker: ^1.5.1
  loader_overlay: ^2.0.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_only.png"

flutter_native_splash:
  background_image: "assets/images/Read Novel splashscreen.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/gifs/
#    - assets/svgs/
