// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlOky2sF6rzDE1FSUCDCHvCtUCHyuk4zw',
    appId: '1:793399712102:android:06a0baf61f8c40686dd0a7',
    messagingSenderId: '793399712102',
    projectId: 'readnovel-4ba84',
    storageBucket: 'readnovel-4ba84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmoshH_1IgcxMJx69w_AmAhhkQ7guxpms',
    appId: '1:793399712102:ios:060986561e6c9e266dd0a7',
    messagingSenderId: '793399712102',
    projectId: 'readnovel-4ba84',
    storageBucket: 'readnovel-4ba84.appspot.com',
    androidClientId: '793399712102-3an5gaavm3huq39fcjqg3j9qnrhjogon.apps.googleusercontent.com',
    iosClientId: '793399712102-hbqho0rg4arg0supfl7sl4l5u13v1lp0.apps.googleusercontent.com',
    iosBundleId: 'com.readnovel.readNovel',
  );
}
